### ISSUE TITLE
Mage: Prismatic Barrier

### ISSUE THREAD

**Issue by fnordson** [Softrix/SmartBuff-Retail#9] opened 2023-01-21 11:46 UTC
Thanks for reviving the add-on. 

Would it be possible to get back Prismatic Barrier for the mage again?  
I've been using the scroll function to launch it during combat so I didn't have to look for it's cool down or use a button. 
Now mages have even more spells and use even more buttons and it would be very useful.

**Comment by speedwaystar** [comment] 2023-01-24 10:54
sure. another user had an issue with this, or was that you? 
![](https://i.imgur.com/BFYbcAB.png)
it's definitely in the code, so i'll double check that it's working as intended

**Comment by speedwaystar** [comment] 2023-01-24 11:03
![](https://i.imgur.com/06EhyiM.png)
![](https://i.imgur.com/JHXmJ9O.png)
![](https://i.imgur.com/FLBGFE8.png)
can you give me some more info about what exactly is happening? is it not appearing in your buff list? is it not prompting you to cast when it's ticked? is it not working in combat?

**Comment by fnordson** [comment] 2023-01-24 16:17
![grafik](https://user-images.githubusercontent.com/5624605/214347704-50e16a6e-953d-49c1-aa00-1a8ec17f4bc9.png)

It is not appearing my my buff list at all anymore. 
As you can see in the screenshot it should be there as I can cast it.

**Comment by speedwaystar** [comment] 2023-01-25 12:58
downloading the 7gb deDE localization now...

**Comment by speedwaystar** [comment] 2023-01-25 13:27
hmmm
![](https://i.imgur.com/HLKLIqr.png)
![](https://i.imgur.com/BfMjB02.png)
at this point i really have no idea why your version isn't working, sorry

**Comment by speedwaystar** [comment] 2023-01-25 13:32
my current alpha is very different from the release and is not at all ready for public consumption, but i might send you a copy once i've fixed a few things which are actively breaking it and you can let me know if Prismatic Barrier works in the alpha.
i'm not sure if you've mentioned this before, but do try running with all other addons switched off, because one of the very few possible reasons for this kind of bug that i can think of is another addon polluting the shared global namespace.

**Comment by fnordson** [comment] 2023-01-25 17:27
Sorry I forgot to write that above: I tried turning all other addons off. 
I just tried again with the newer version (See screenshot in comment above). 
I also deleted related files in SavedVariables.
Unfortunately it didn't help. 

FYI: your smart buff addon worked with prismatic barrier once in Dragonflight.  
It stopped after one of the updates. I just didn't write a bug report because I thought I might play without it. 

I'd appreciate your alpha.

**Comment by speedwaystar** [comment] 2023-02-02 22:49
sorry @fnordson can you reopen the ticket? it hasn't been fixed internally yet. we'll close it when fix is pushed to the main release. cheers.

**Comment by fnordson** [comment] 2023-02-03 21:04
It works! 
Thank you :)

**Comment by speedwaystar** [comment] 2023-02-04 00:55
cheers! you can close the ticket now :D

**Closed** 2023-02-04 14:03 UTC
