### ISSUE TITLE
SB does not initialize correctly since R17+ ?!

### ISSUE THREAD

**Issue by spastik303** [Softrix/SmartBuff-Retail#21] opened 2023-02-25 11:40 UTC
Hello,

I haven't been able to find anything relating to this issue so I figured I'd come here to report it.

My Smartbuff will not detect that buffs are required unless I do a "reset all" every session.  (I have to do this every time I log on to a character for it to start working again)  No splash screen, no manual activation of the button; it's as if the mod stays dormant until I do said "reset all".

I've tried clean UI / deleting every WTF / Addon / Saved Variable folder and doing ultra clean install, etc... It does work in r16, but r17 and above does not.

Any insight would be appreciated, love the mod.  (Running R16 for now to get around the issue)

TY

**Comment by speedwaystar** [comment] 2023-02-27 10:55
that's extremely bizarre. i can't reproduce that behaviour at all. can you tell me your class, level and what language the client is set to?

**Comment by spastik303** [comment] 2023-02-27 14:56
It's all classes and specs, english.

I did not try clearing the global "wow" variables... something in "hidden" console options may be at fault?  Let me try that tonight and report back.

**Comment by spastik303** [comment] 2023-02-27 22:19
Hello,

OK, after a bunch of trial and error testing I think I've narrowed down how the mod doesn't work for me.

If I load into a character while the "Switch template" checkbox is UNCHECKED. then the mod does not check if any buffs are required until I open /SB Menu and check said box... after which it kicks in and starts working again.

Hope this helps narrow it down.  Thank you!

**Comment by ynazar1** [comment] 2023-02-28 21:10
This has been fixed in the code, though I'm not sure if that's been pushed to curse. @speedwaystar 's code is in the main branch. Grab the code zip and replace the files in your addon folder for now.

**Comment by spastik303** [comment] 2023-02-28 21:37
Super, thank you!  (Sorry for not making intially making the link to the prior reported issue!)

**Comment by speedwaystar** [comment] 2023-03-01 10:53
just pinging @Softrix to double check that the latest build is live on Curse: refer discussion above.

**Comment by Softrix** [comment] 2023-03-01 11:12
Last version reaching curse was r19 which included the GetSpellBookItemName change among other changes, this was the last pull request I have received since then, uploaded Feb 3, 2023 so if there has been any new pull requests since then I have sadly not got them again from github (just checked again, nothing pending).

**Comment by speedwaystar** [comment] 2023-03-01 11:28
you're basically up to date then. my subsequent commits aren't relevant to the issue at hand.
https://github.com/Softrix/SmartBuff-Retail/compare/main...speedwaystar:SmartBuff-Retail:main

**Comment by Softrix** [comment] 2023-03-01 12:44
Request merged and pushed to Curse in r20

**Comment by Softrix** [comment] 2023-03-01 12:45
just to make sure  :)

**Comment by spastik303** [comment] 2023-03-01 14:01
Amazing; very appreciated! :)

**Comment by Softrix** [comment] 2023-03-01 14:19
Perfect, closing.

**Closed by Softrix** 2023-03-01 14:19 UTC

**Comment by ynazar1** [comment] 2023-03-01 17:24
Thanks all. 
Looking at dates, r19 was released to curse on Feb 3rd and #14 got fixed on Feb 4th... We were beta-testing in Discord and everything worked but forgot to push it up to curse after confirmed fixed. Glad it's all resolved now.
